services:
  sewagurubackendsand:
    image: sewagurubackendsand
    container_name: sewagurubackendsand
    build: .
    restart: unless-stopped
    ports:
      - "5001:5000"
    env_file:
      - .env.production